<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <FullFrameworkTFM>net472</FullFrameworkTFM>
    <!-- enforce CamelCase case string-->
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Copyright>(c) 2018 Toni Solarin-Sodara</Copyright>
    <!-- SourceLink Setup -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <!-- Build properties -->
    <MSBuildTreatWarningsAsErrors>true</MSBuildTreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);NU1507;NU5105;CS1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--<UsingMicrosoftArtifactsSdk>true</UsingMicrosoftArtifactsSdk>-->
    <!-- https://learn.microsoft.com/en-us/dotnet/core/sdk/artifacts-output -->
    <!-- C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.DefaultOutputPaths.targets -->
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <ArtifactsBinOutputName>bin</ArtifactsBinOutputName>
    <!-- Breaking change NET 8.0 InformationalVersion with SourceRevisionId -->
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <!-- Default to non-deterministic for local builds -->
  <PropertyGroup Condition="'$(TF_BUILD)' != 'true' AND '$(GITHUB_ACTIONS)' != 'true'">
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
    <Deterministic>false</Deterministic>
    <DeterministicSourcePaths>false</DeterministicSourcePaths>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

</Project>
