// Copyright (c) Toni Solarin-Sodara
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// Remember to use full name because adding new using directives change line numbers

namespace Coverlet.Core.CoverageSamples.Tests
{
  /// <summary>
  /// Test class for issue #1762: Instrumentation crash with LibraryImport/DllImport methods without IL body.
  /// When a method has no body (like extern methods generated by LibraryImport/DllImport) and is marked
  /// with ExcludeFromCodeCoverage, the instrumenter should not throw a NullReferenceException.
  /// </summary>
  public class MethodsWithExcludeFromCodeCoverageAttr_NativeInterop
  {
    /// <summary>
    /// A regular method that can be executed to test instrumentation.
    /// </summary>
    public int RegularMethod(int value)
    {
      return value + 1;
    }

    /// <summary>
    /// An excluded local function that contains a lambda - this exercises the
    /// CollectLambdaMethodsInsideLocalFunction code path when the method has a body.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public int ExcludedLocalFunctionWithLambda(string input)
    {
      return LocalFunction(input);

      static int LocalFunction(string s)
      {
        System.Func<string, int> lambdaFunc = x => x.Length;
        return lambdaFunc(s);
      }
    }

    /// <summary>
    /// An excluded extern method using DllImport. This method has no IL body.
    /// Issue #1762: This was causing NullReferenceException in CollectLambdaMethodsInsideLocalFunction.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.Runtime.InteropServices.DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool GetDiskFreeSpaceExA(
      string lpDirectoryName,
      out ulong lpFreeBytesAvailableToCaller,
      out ulong lpTotalNumberOfBytes,
      out ulong lpTotalNumberOfFreeBytes);

    /// <summary>
    /// A regular method to verify other methods are still instrumented correctly.
    /// </summary>
    public int AnotherRegularMethod(int a, int b)
    {
      return a + b;
    }

    /// <summary>
    /// Public method to run tests - returns sum to prove instrumentation works.
    /// </summary>
    public int Test(int value)
    {
      return RegularMethod(value) + AnotherRegularMethod(value, value);
    }
  }

  /// <summary>
  /// A static class with DllImport methods to test extern method scenarios.
  /// </summary>
  public static class NativeMethodsWithExcludeAttribute
  {
    /// <summary>
    /// A regular static method that can be instrumented.
    /// </summary>
    public static int StaticMethod(int value)
    {
      return value * 2;
    }

    /// <summary>
    /// An excluded extern method using DllImport.
    /// Issue #1762: This was causing NullReferenceException during instrumentation.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.Runtime.InteropServices.DllImport("kernel32.dll", EntryPoint = "GetCurrentProcessId")]
    public static extern uint GetCurrentProcessIdExcluded();

    /// <summary>
    /// A method with exclude that has a local function containing a lambda.
    /// This tests that CollectLambdaMethodsInsideLocalFunction handles methods with bodies.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static int ExcludedMethodWithLocalFunctionAndLambda(string input)
    {
      return GetLength(input);

      static int GetLength(string s)
      {
        System.Func<string, int> len = str => str.Length;
        return len(s);
      }
    }
  }
}
