steps:
- task: UseDotNet@2
  inputs:
    version: 3.1.404
  displayName: Install .NET Core SDK 3.1.404

- task: UseDotNet@2
  inputs:
    version: 5.0.101
  displayName: Install .NET Core SDK 5.0.101

- script: dotnet restore
  displayName: Restore packages

- script: dotnet build -c $(BuildConfiguration) --no-restore
  displayName: Build

- script: dotnet pack -c $(BuildConfiguration) --no-restore
  displayName: Pack

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test
    arguments: -c $(BuildConfiguration) --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include="[coverlet.collector]*%2c[coverlet.core]*%2c[coverlet.msbuild.tasks]*" /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.xunit.extensions]*"
    testRunTitle: $(Agent.JobName)
