steps:
- task: UseDotNet@2
  inputs:
    version: 8.0.416
  displayName: Install .NET Core SDK 8.0.416

- task: UseDotNet@2
  inputs:
    useGlobalJson: true
  displayName: Install .NET Core SDK (global.json)

# create artifact/package folder
- pwsh: |
    New-Item -ItemType Directory -Path artifacts/package/debug -Force
    New-Item -ItemType Directory -Path artifacts/package/release -Force
  displayName: create folder artifacts/package/$(BuildConfiguration)

# Authenticate Azure DevOps NuGet feed
- task: NuGetAuthenticate@1
  displayName: 'Authenticate Azure DevOps NuGet feed'
  inputs:
    forceReinstallCredentialProvider: true

- script: dotnet restore -v n -s "https://api.nuget.org/v3/index.json"
  displayName: Restore packages

# - task: DotNetCoreCLI@2
#   displayName: Restore packages
#   inputs:
#     command: restore
#     projects: 'coverlet.sln'
#     feedsToUse: 'config'
#     nugetConfigPath: 'nuget.config'

- script: dotnet build -c $(BuildConfiguration) --no-restore -bl:build.msbuild.binlog
  displayName: Build

- script: dotnet pack -c $(BuildConfiguration) --no-restore
  displayName: Pack

     # investigate: How to generate code coverage results not using coverlet.msbuild.tasks
     # artifacts\bin\coverlet.MTP.unit.tests\debug\coverlet.MTP.unit.tests.exe --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.MTP.unit.tests.trx" --diagnostic --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/$(BuildConfiguration)" --diagnostic-file-prefix "coverlet.MTP.unit.tests_"

- script: |
    dotnet test test/coverlet.MTP.unit.tests/coverlet.MTP.unit.tests.csproj -c $(BuildConfiguration) --no-build -bl:test.unit.MTP.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:ExcludeByAttribute="GeneratedCodeAttribute" -- --results-directory "$(Build.SourcesDirectory))/artifacts/reports" --report-xunit-trx --report-xunit-trx-filename "coverlet.MTP.unit.tests.trx" --diagnostic-verbosity trace  --diagnostic --diagnostic-output-directory "./artifacts/log/$(BuildConfiguration)" --diagnostic-file-prefix "coverlet.MTP.unit.tests_"  
    dotnet test test/coverlet.core.tests/coverlet.core.tests.csproj -c $(BuildConfiguration) --no-build -bl:test.core.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --diag:"$(Build.SourcesDirectory)/artifacts/log/$(BuildConfiguration)/coverlet.core.tests.diag;tracelevel=verbose"
    dotnet test test/coverlet.core.coverage.tests/coverlet.core.coverage.tests.csproj -c $(BuildConfiguration) --no-build -bl:test.core.coverage.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" -- --results-directory "$(Build.SourcesDirectory))/artifacts/reports" --report-xunit-trx --report-xunit-trx-filename "coverlet.core.coverage.tests.trx" --diagnostic-verbosity trace  --diagnostic --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/$(BuildConfiguration)" --diagnostic-output-fileprefix "coverlet.core.coverage.tests_"
    dotnet test test/coverlet.msbuild.tasks.tests\coverlet.msbuild.tasks.tests.csproj -c $(BuildConfiguration) --no-build -bl:test.msbuild.tasks.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --diag:"$(Build.SourcesDirectory)/artifacts/log/$(BuildConfiguration)/coverlet.msbuild.tasks.tests.diag;tracelevel=verbose"
    dotnet test test/coverlet.collector.tests/coverlet.collector.tests.csproj -c $(BuildConfiguration) --no-build -bl:test.collector.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.collector.tests.diag.$(BuildConfiguration).log;tracelevel=verbose"
    dotnet test test/coverlet.integration.tests/coverlet.integration.tests.csproj -c $(BuildConfiguration) -f net8.0 --no-build -bl:test.integration.binlog --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.integration.tests.diag.net8.0.$(BuildConfiguration).log;tracelevel=verbose"
    dotnet test test/coverlet.integration.tests/coverlet.integration.tests.csproj -c $(BuildConfiguration) -f net9.0 --no-build -bl:test.integration.binlog --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.integration.tests.diag.net9.0.$(BuildConfiguration).log;tracelevel=verbose"
    dotnet exec "$(Build.SourcesDirectory)/artifacts/bin/coverlet.MTP.validation.tests/$(BuildConfiguration)/coverlet.MTP.validation.tests.dll" --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.MTP.validation.tests.trx" --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/$(BuildConfiguration)" --diagnostic-file-prefix "coverlet.MTP.validation.tests_"
  displayName: Run unit tests with coverage
  env:
    MSBUILDDISABLENODEREUSE: 1

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    mergeTestResults: false
    publishRunAttachments: true
    failTaskOnFailedTests: true
    testRunTitle: $(Agent.OS)_$(BuildConfiguration)
  condition:  succeededOrFailed()

- template: publish-coverlet-result-files.yml

- template: publish-coverage-results.yml
  parameters:
    reports: $(Build.SourcesDirectory)\**\*.opencover.xml
    condition: and(succeededORFailed(), eq(variables['buildConfiguration'], 'debug'), eq(variables['agent.os'], 'Windows_NT'))
    minimumLineCoverage: 90
    assemblyfilters: '-xunit;-coverlet.testsubject;-Coverlet.Tests.ProjectSample.*;-coverlet.core.tests.samples.netstandard;-coverletsamplelib.integration.template;-coverlet.tests.utils'

