steps:
- task: UseDotNet@2
  inputs:
    version: 2.2.207
  displayName: Install .NET Core SDK

- task: UseDotNet@2
  inputs:
    version: 3.1.100
  displayName: Install .NET Core SDK

- script: dotnet restore
  displayName: Restore packages

- script: dotnet build -c $(BuildConfiguration) --no-restore
  displayName: Build

- script: dotnet pack -c $(BuildConfiguration)
  displayName: Pack

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    arguments: -c $(BuildConfiguration) --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include="[coverlet.collector]*2%c[coverlet.core]*2%c[coverlet.msbuild.tasks]*" /p:Exclude="[coverlet.core.tests.samples.netstandard]*2%c[coverlet.tests.remoteexecutor]*"
    testRunTitle: $(Agent.JobName)