steps:
- task: UseDotNet@2
  inputs:
    version: 6.0.413
  displayName: Install .NET Core SDK 6.0.413

- task: UseDotNet@2
  inputs:
    version: 7.0.400
  displayName: Install .NET Core SDK 7.0.400

- script: dotnet restore
  displayName: Restore packages

- script: dotnet build -c $(BuildConfiguration) --no-restore
  displayName: Build

- script: dotnet pack -c $(BuildConfiguration) --no-restore
  displayName: Pack

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test
    arguments: -c $(BuildConfiguration) --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Include="[coverlet.collector]*%2c[coverlet.core]*%2c[coverlet.msbuild.tasks]*" /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.xunit.extensions]*"
    testRunTitle: $(Agent.JobName)

- template: publish-coverlet-result-files.yml

#- template: publish-coverage-results.yml
#  parameters:
#    reports: $(Build.SourcesDirectory)/**/coverage.opencover.xml
#    condition: and(succeeded(), eq(variables['_BuildConfig'], 'Debug'))
#    assemblyfilters: '-xunit*;+Coverlet.Core.*;+Coverlet.Collector.*'
