steps:
- task: UseDotNet@2
  inputs:
    version: 8.0.417
  displayName: Install .NET Core SDK 8.0.417

- task: UseDotNet@2
  inputs:
    version: 9.0.311
  displayName: Install .NET Core SDK 9.0.311

- task: UseDotNet@2
  inputs:
    useGlobalJson: true
  displayName: Install .NET Core SDK (global.json)

# create artifact/package folder
- pwsh: |
    New-Item -ItemType Directory -Path artifacts/package/debug -Force
    New-Item -ItemType Directory -Path artifacts/package/release -Force
  displayName: create folder artifacts/package/$(BuildConfiguration)

# Authenticate Azure DevOps NuGet feed
- task: NuGetAuthenticate@1
  displayName: 'Authenticate Azure DevOps NuGet feed'
  inputs:
    forceReinstallCredentialProvider: true

- script: dotnet restore -v n -s "https://api.nuget.org/v3/index.json"
  displayName: Restore packages

- script: dotnet build -c $(BuildConfiguration) --no-restore -bl:build.msbuild.binlog
  displayName: Build

- script: dotnet pack -c $(BuildConfiguration) --no-restore
  displayName: Pack

# - script: |
#     dotnet build-server shutdown
#     dotnet test test/coverlet.MTP.tests/coverlet.MTP.tests.csproj -c $(BuildConfiguration) -f net8.0 --no-build -bl:test.MTP.net8.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.MTP.tests.net8.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.MTP.tests.net8.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.MTP.tests/coverlet.MTP.tests.csproj -c $(BuildConfiguration) -f net9.0 --no-build -bl:test.MTP.net9.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.MTP.tests.net9.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.MTP.tests.net9.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.core.tests/coverlet.core.tests.csproj -c $(BuildConfiguration) -f net8.0 --no-build -bl:test.core.net8.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.core.tests.net8.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.core.tests.net8.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.core.tests/coverlet.core.tests.csproj -c $(BuildConfiguration) -f net9.0 --no-build -bl:test.core.net9.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.core.tests.net9.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.core.tests.net9.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.core.coverage.tests/coverlet.core.coverage.tests.csproj -c $(BuildConfiguration) -f net8.0 --no-build -bl:test.core.coverage.net8.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.core.coverage.tests.net8.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.core.coverage.tests.net8.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.core.coverage.tests/coverlet.core.coverage.tests.csproj -c $(BuildConfiguration) -f net9.0 --no-build -bl:test.core.coverage.net9.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.core.coverage.tests.net9.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.core.coverage.tests.net9.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.msbuild.tasks.tests/coverlet.msbuild.tasks.tests.csproj -c $(BuildConfiguration) -f net8.0 --no-build -bl:test.msbuild.tasks.net8.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.msbuild.tasks.tests.net8.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.msbuild.tasks.tests.net8.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.msbuild.tasks.tests/coverlet.msbuild.tasks.tests.csproj -c $(BuildConfiguration) -f net9.0 --no-build -bl:test.msbuild.tasks.net9.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.msbuild.tasks.tests.net9.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.msbuild.tasks.tests.net9.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.collector.tests/coverlet.collector.tests.csproj -c $(BuildConfiguration) -f net8.0 --no-build -bl:test.collector.net8.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.collector.tests.net8.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.collector.tests.net8.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.collector.tests/coverlet.collector.tests.csproj -c $(BuildConfiguration) -f net9.0 --no-build -bl:test.collector.net9.0.binlog /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude="[coverlet.core.tests.samples.netstandard]*%2c[coverlet.tests.projectsample]*" /p:ExcludeByAttribute="GeneratedCodeAttribute" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.collector.tests.net9.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.collector.tests.net9.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.integration.tests/coverlet.integration.tests.csproj -c $(BuildConfiguration) -f net8.0 --no-build -bl:test.integration.net8.0.binlog --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.integration.tests.net8.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.integration.tests.net8.0.diag;tracelevel=verbose"
#     dotnet test test/coverlet.integration.tests/coverlet.integration.tests.csproj -c $(BuildConfiguration) -f net9.0 --no-build -bl:test.integration.net9.0.binlog --results-directory "$(Build.SourcesDirectory)/artifacts/reports/" --logger "trx;LogFileName=coverlet.integration.tests.net9.0.trx" --diag:"$(Build.SourcesDirectory)/artifacts/log/coverlet.integration.tests.net9.0.diag;tracelevel=verbose"
#   displayName: Run unit tests with coverage (net8.0/net9.0)
#   env:
#     MSBUILDDISABLENODEREUSE: 1

# Run tests without coverage using dotnet exec 
- pwsh: |
    $frameworks = "$(frameworks)".Split(",")
        foreach ($fw in $frameworks) {
            dotnet build-server shutdown
            Write-Host "Testing $fw"  
            dotnet exec "$(Build.SourcesDirectory)/artifacts/bin/coverlet.MTP.tests/$(BuildConfiguration)_${fw}/coverlet.MTP.tests.dll" --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.MTP.tests.${fw}.trx" --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/" --diagnostic-file-prefix "coverlet.MTP.tests.${fw}_" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/"
            dotnet build-server shutdown
            dotnet exec "$(Build.SourcesDirectory)/artifacts/bin/coverlet.core.tests/$(BuildConfiguration)_${fw}/coverlet.core.tests.dll" --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.core.tests.${fw}.trx" --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/" --diagnostic-file-prefix "coverlet.core.tests.${fw}_" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/"
            dotnet build-server shutdown
            dotnet exec "$(Build.SourcesDirectory)/artifacts/bin/coverlet.core.coverage.tests/$(BuildConfiguration)_${fw}/coverlet.core.coverage.tests.dll" --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.core.coverage.tests.${fw}.trx" --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/" --diagnostic-file-prefix "coverlet.core.coverage.tests.${fw}_" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/"
            dotnet build-server shutdown
            dotnet exec "$(Build.SourcesDirectory)/artifacts/bin/coverlet.msbuild.tasks.tests/$(BuildConfiguration)_${fw}/coverlet.msbuild.tasks.tests.dll" --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.msbuild.tasks.tests.${fw}.trx" --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/" --diagnostic-file-prefix "coverlet.msbuild.tasks.tests.${fw}_" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/"
            dotnet build-server shutdown
            dotnet exec "$(Build.SourcesDirectory)/artifacts/bin/coverlet.collector.tests/$(BuildConfiguration)_${fw}/coverlet.collector.tests.dll" --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.collector.tests.${fw}.trx" --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/" --diagnostic-file-prefix "coverlet.collector.tests.${fw}_" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/"
            dotnet build-server shutdown
            dotnet exec "$(Build.SourcesDirectory)/artifacts/bin/coverlet.integration.tests/$(BuildConfiguration)_${fw}/coverlet.integration.tests.dll" --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.integration.tests.${fw}.trx" --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/" --diagnostic-file-prefix "coverlet.integration.tests.${fw}_" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/"
            # dotnet build-server shutdown
            # dotnet exec "$(Build.SourcesDirectory)/artifacts/bin/coverlet.MTP.validation.tests/$(BuildConfiguration)_${fw}/coverlet.MTP.validation.tests.dll" --diagnostic --diagnostic-verbosity trace --report-xunit-trx --report-xunit-trx-filename "coverlet.MTP.validation.tests.${fw}.trx" --diagnostic-output-directory "$(Build.SourcesDirectory)/artifacts/log/" --diagnostic-file-prefix "coverlet.MTP.validation.tests.${fw}_" --results-directory "$(Build.SourcesDirectory)/artifacts/reports/"
            }
  displayName: Run unit tests without coverage
  env:
    MSBUILDDISABLENODEREUSE: 1

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    searchFolder: '$(Build.SourcesDirectory)'
    mergeTestResults: true
    publishRunAttachments: true
    failTaskOnFailedTests: true
    testRunTitle: $(Agent.OS)_$(BuildConfiguration)
  condition:  succeededOrFailed()

- template: publish-coverlet-result-files.yml

- script: |
    dir /s /B *.xml
    del coverlet.integration.determisticbuild\coverage.net8.0.cobertura.xml
    del coverlet.integration.determisticbuild\coverage.net9.0.cobertura.xml
    del coverlet.integration.determisticbuild\coverage.net10.0.cobertura.xml
  displayName: List XML files for test folder
  workingDirectory: "$(Build.SourcesDirectory)/test"
  condition: and(succeededOrFailed(), eq(variables['buildConfiguration'], 'debug'), eq(variables['agent.os'], 'Windows_NT'))

- template: publish-coverage-results.yml
  parameters:
    reports: "$(Build.SourcesDirectory)/test/**/*.cobertura.xml"
    condition: and(succeededOrFailed(), eq(variables['buildConfiguration'], 'debug'), eq(variables['agent.os'], 'Windows_NT'))
    minimumLineCoverage: 80
    assemblyfilters: '-xunit;-coverlet.testsubject;-Coverlet.Tests.ProjectSample.*;-coverlet.core.tests.samples.netstandard;-coverletsamplelib.integration.template;-coverlet.tests.utils;-coverletsample.integration.determisticbuild'

